---
title: "Comprehensive benchmarking of motif instances (all types) - only IntAct and Vidal"
author: "Vitalii Kleshchevnikov"
date: "18/10/2017"
output: 
  html_document: 
    keep_md: yes
    toc: yes
---

```{r setup, include=TRUE}
knitr::opts_chunk$set(fig.width = 12, fig.height = 8, warning = FALSE, message = FALSE)

packages = c("MItools", "RColorBrewer", "devtools", "grid","gridExtra", "ggplot2", "VennDiagram", "svglite")
if(mean(packages %in% names(installed.packages()[,"Package"])) != 1){
    packages_to_install = packages[!packages %in% names(installed.packages()[,"Package"])]
    # specifying mirror is necessary for some Linux systems
    install.packages(packages_to_install, dependencies = T, repos = "http://mirrors.ebi.ac.uk/CRAN/")
    packages_to_install = packages[!packages %in% names(installed.packages()[,"Package"])]
    source("https://bioconductor.org/biocLite.R")
    biocLite(packages_to_install)
    devtools::install_github("vitkl/MItools", dependencies = T)
}
suppressPackageStartupMessages({
    library(MItools)
    library(grid)
    library(gridExtra)
    library(ggplot2)
})

colors = RColorBrewer::brewer.pal(2, "Dark2")

motif_types = c("MOD", "LIG", "DOC") # "MOD", "LIG", "DOC" / "DEG", "CLV", "TRG"
normalise = F # if normalised Sig threshold of 0.3 becomes 1 (but this equalises Sig == 0.3 to true 1 - that is when motif was not found)
#ROC:
measure1 = "prec" # "tpr" or "prec"
measure2 = "rec" # "fpr" or "rec"
both_metrics_vs_cutoff = T
single_metric = c("auc","prbe")[1]
single_metric_name = c("Median AUC", "Prec-rec break-even")[1]

datasets = c("qslimfinder.Full_IntAct3.FALSE",
             "qslimfinder.Vidal3.FALSE",
             "qslimfinder.all_viral_interaction3.FALSE")
descriptions = c("human network (full IntAct) searched \nfor motifs present in viral proteins",
                 "human network (Vidal's data only) searched \nfor motifs present in viral proteins",
                 "human network (human-viral data only) searched \nfor motifs present in viral proteins")
motif_setup_month = c("201802",
                      "201802",
                      "201802")
```

## Overview

### 
1. filter_by_domain_data: NULL or "p.value < 0.5"
2. neg_set: "all_instances", "all_proteins"
3. motif_pval_cutoff: 1, precision == recall, precision > 0.5

```{r, not_filt_Sig}
#####################################################################################
myBenchmarkMotifs = function(neg_set, filter_by_domain_data, motif_pval_cutoff, dataset, datasets, return_all = F, merge_domain_data = F){
    res = mBenchmarkMotifs(datasets = dataset, 
                           descriptions = descriptions[datasets == dataset],
                           dir = "./", 
                           merge_domain_data = merge_domain_data, neg_set = neg_set,
                           domain_res_file = "./processed_data_files/what_we_find_VS_ELM_clust20171019.RData",
                           domain_results_obj = "res_count", motif_input_obj = "forSLIMFinder_Ready",
                           one_from_cloud = T, type = "QSLIMFinder",
                           dbfile_main = "./data_files/instances9606.gff",
                           dburl_main = "http://elm.eu.org/instances.gff?q=None&taxon=Homo%20sapiens&instance_logic=",
                           dbfile_query = "./data_files/instances10239.gff",
                           dburl_query = "http://elm.eu.org/instances.gff?q=all&taxon=irus&instance_logic=",
                           query_res_query_only = T, motif_types = motif_types,
                           all_res_excl_query = T,
                           seed = 21, N = N_negative_sets, replace = T, within1sequence = T,
                           query_predictor_col = "Sig", all_predictor_col = "Sig", normalise = normalise,
                           minoverlap = 2, maxgap = 0, motif_setup_months = motif_setup_month[datasets == dataset],
                           count_ranges_by = list(by = "IDs_domain_human", name = "motif_occ_per_domain",
                                                  normalise_by = "domain_count", normalised_name = "normalised_motif_occ_per_domain"),
                           filter_by_domain_data = filter_by_domain_data,
                           motif_pval_cutoff = motif_pval_cutoff)
    DT = data.table(N_query_prot_with_known_instances = res[[1]]$N_query_prot_with_known_instances,
               N_query_known_instances = res[[1]]$N_query_known_instances,
               N_query_prot_with_known_instances_found = res[[1]]$N_query_prot_with_known_instances_found,
               N_query_found_match_known_instances = res[[1]]$N_query_known_instances_found,
               N_query_total_instances_found = res[[1]]$N_query_total_instances_found,
               N_query_known_match_instances_found = res[[1]]$N_query_match_known_instances_found)
    if(return_all) list(res = res, DT = DT) else return(DT)
}
#####################################################################################
res_list_viral = myBenchmarkMotifs(neg_set = "all_instances",
                                   filter_by_domain_data = NULL,
                                   motif_pval_cutoff = 1,
                                   dataset = datasets[1], datasets)
#####################################################################################
plotVenn = function(res, ...){
    #grid.newpage()
    if(res$N_query_total_instances_found < res$N_query_known_instances) rotation.degree = 180 else rotation.degree = 0
    venn.plot <- VennDiagram::draw.pairwise.venn(
        area1 = res$N_query_total_instances_found,
        area2 = res$N_query_known_instances,
        cross.area = res$N_query_known_match_instances_found,
        category = c("discovered instances", "known instances"),
        fill = c("royalblue1", "seagreen1"),
        euler.d = F, scaled = F,
        lty = "blank",
        cat.pos = c(340, 175),
        cat.dist = c(0.05,0.05),
        ext.pos = 10,
        ext.dist = -0.05,
        ext.length = 0.8,
        ext.line.lwd = 2,
        ext.line.lty = "dashed",
        rotation.degree = rotation.degree,
        ind = F,
        ...
    );
    #grid.newpage()
    venn = gTree(children=venn.plot, name="venn")
    #grid.newpage()
    # since multiple matches are possible between datasets I need to edit numbers shown on a diagram
    venn = editGrob(venn, paste0(venn[["childrenOrder"]][7]),
                    label = paste0(res$N_query_found_match_known_instances,
                                   " / ",res$N_query_known_match_instances_found),
                    grep = T)
    #grid.newpage()
    if(rotation.degree == 0) discovered_ind = 5 else discovered_ind = 6
    venn = editGrob(venn, paste0(venn[["childrenOrder"]][discovered_ind]),
                    label = res$N_query_total_instances_found - res$N_query_found_match_known_instances,
                    grep = T)
    #grid.newpage()
    #grid.draw(venn)
    return(venn)
}
#####################################################################################
plotVenn(res_list_viral)
#####################################################################################
plotAnnotVenn = function(res, main = "", sub = "",
                         main_fontsize = 22, sub_fontsize = 17,
                         main_lineheight = 1.4, sub_lineheight = 0.9,
                         cex = 1.8, cat.cex = 1.8,
                         fontfamily = "Arial", ...) { # "serif" "Arial"
    
    lay = matrix(c(1), nrow = 1, ncol = 1)
    annotated_venn = plotVenn(res, fontfamily = fontfamily, cat.fontfamily = fontfamily,
                              cex = cex, cat.cex = cat.cex)
    if(sub != "") {
        lay = matrix(c(1,2,2,2,2,2), nrow = 6, ncol = 1)
        sub_grob = textGrob(sub,
                            gp=gpar(fontsize=sub_fontsize, fontfamily = fontfamily,
                                    lineheight = sub_lineheight, ...))
        annotated_venn = gridExtra::arrangeGrob(sub_grob,
                                                annotated_venn, ncol=1,
                                                layout_matrix = lay)
    }
    
    if(main != ""){
        lay = matrix(c(1,2,2,2,2,2), nrow = 6, ncol = 1)
        main_grob = textGrob(main,
                             gp=gpar(fontsize=main_fontsize, fontfamily = fontfamily,
                                     lineheight = main_lineheight, ...))
        annotated_venn = gridExtra::arrangeGrob(main_grob,
                                                annotated_venn, ncol=1,
                                                layout_matrix = lay)
    } 
    
    #grid.newpage()
    #grid.draw(annotated_venn)
    return(annotated_venn)
}
#####################################################################################
plotAnnotVenn(res_list_viral, main = "corrected p-value < 0.3")
#####################################################################################
mPlotAnnotVenn = function(filter_by_domain_data = NULL,
                          motif_pval_cutoffs = c(0.3, 0.05, 0.002),
                          motif_pval_tags = c("lenient cutoff", "optimal cutoff", "stringent cutoff"),
                          dataset = datasets[1], datasets = datasets, fontfamily = "Arial") {
        annotated_venns = lapply(motif_pval_cutoffs, function(motif_pval_cutoff){
            res_instances = myBenchmarkMotifs(neg_set = "all_instances",
                                              filter_by_domain_data = filter_by_domain_data,
                                              motif_pval_cutoff = motif_pval_cutoff,
                                              dataset = dataset, datasets)
            res_proteins = myBenchmarkMotifs(neg_set = "all_proteins",
                                             filter_by_domain_data = filter_by_domain_data,
                                             motif_pval_cutoff = motif_pval_cutoff,
                                             dataset = dataset, datasets)
            annotated_venn = plotAnnotVenn(res_instances,
                                           main = paste0(motif_pval_tags[motif_pval_cutoffs == motif_pval_cutoff],
                                                         ": adj. p-value < ", signif(motif_pval_cutoff, 2)),
                                           sub = paste0(res_instances$N_query_prot_with_known_instances,
                                                        " proteins with known SLIMs (",
                                                        res_instances$N_query_prot_with_known_instances_found," proteins recovered)\n",
                                                        res_proteins$N_query_total_instances_found," SLIMs predicted in other proteins"),
                                           fontfamily = fontfamily)
        })
        gridExtra::arrangeGrob(grobs = annotated_venns, ncol=1)
}
#####################################################################################
figureVenn = function(filter_by_domain_data = NULL,
                      main = "",
                      motif_pval_tags = c("lenient cutoff", "optimal cutoff", "stringent cutoff"),
                      datasets = datasets,
                      stringent_prec = 0.5,
                      lenient_cutoff = 0.3,
                      motif_pval_cutoffs_IntAct = NULL,
                      motif_pval_cutoffs_Vidal = NULL,
                      motif_pval_cutoffs_viral = NULL,
                      fontfamily = "Arial", ...){
    ################################################################################ IntAct
    res_list_IntAct = myBenchmarkMotifs(neg_set = "all_instances",
                                        filter_by_domain_data = filter_by_domain_data,
                                        motif_pval_cutoff = 1,
                                        dataset = datasets[1], datasets, return_all = T)
    rocr_list_IntAct = mBenchmarkMotifsROC(res_list_IntAct$res, measure1 = "prec", measure2 = "rec", ROCR_data = T)
    if(is.null(motif_pval_cutoffs_IntAct)){
        motif_pval_cutoffs_IntAct = c(lenient_cutoff,
                                      1 - min(rocr_list_IntAct[1,1][[1]]@cutoffs[[1]][rocr_list_IntAct[2,1][[1]]@y.values[[1]] >
                                                                                          rocr_list_IntAct[2,1][[1]]@x.values[[1]]], na.rm = T),
                                      1 - min(rocr_list_IntAct[1,1][[1]]@cutoffs[[1]][rocr_list_IntAct[2,1][[1]]@y.values[[1]] > stringent_prec],
                                              na.rm = T))
    }
    big_plot_IntAct = mPlotAnnotVenn(filter_by_domain_data = filter_by_domain_data,
                                     motif_pval_cutoffs = motif_pval_cutoffs_IntAct,
                                     motif_pval_tags = motif_pval_tags,
                                     dataset = datasets[1], datasets = datasets, fontfamily = fontfamily)
    IntAct_grob = textGrob("including all human data (IntAct)",
                           gp=gpar(fontsize=25, fontfamily = fontfamily,
                                   lineheight = 1.4, ...))
    ################################################################################ Vidal
    res_list_Vidal = myBenchmarkMotifs(neg_set = "all_instances",
                                        filter_by_domain_data = filter_by_domain_data,
                                        motif_pval_cutoff = 1,
                                        dataset = datasets[2], datasets, return_all = T)
    rocr_list_Vidal = mBenchmarkMotifsROC(res_list_Vidal$res, measure1 = "prec", measure2 = "rec", ROCR_data = T)
    if(is.null(motif_pval_cutoffs_Vidal)){
        motif_pval_cutoffs_Vidal = c(lenient_cutoff,
                                      1 - min(rocr_list_Vidal[1,1][[1]]@cutoffs[[1]][rocr_list_Vidal[2,1][[1]]@y.values[[1]] >
                                                                                          rocr_list_Vidal[2,1][[1]]@x.values[[1]]], na.rm = T),
                                      1 - min(rocr_list_Vidal[1,1][[1]]@cutoffs[[1]][rocr_list_Vidal[2,1][[1]]@y.values[[1]] > stringent_prec],
                                              na.rm = T))
    }
    big_plot_Vidal = mPlotAnnotVenn(filter_by_domain_data = filter_by_domain_data,
                                     motif_pval_cutoffs = motif_pval_cutoffs_Vidal,
                                     motif_pval_tags = motif_pval_tags,
                                     dataset = datasets[2], datasets = datasets, fontfamily = fontfamily)
    Vidal_grob = textGrob("including human data (Vidal)",
                           gp=gpar(fontsize=25, fontfamily = fontfamily,
                                   lineheight = 1.4, ...))
    ################################################################################ viral only
    res_list_viral = myBenchmarkMotifs(neg_set = "all_instances",
                                       filter_by_domain_data = filter_by_domain_data,
                                       motif_pval_cutoff = 1,
                                       dataset = datasets[3], datasets, return_all = T)
    rocr_list_viral = mBenchmarkMotifsROC(res_list_viral$res, measure1 = "prec", measure2 = "rec", ROCR_data = T)
    if(is.null(motif_pval_cutoffs_viral)){
        motif_pval_cutoffs_viral = c(lenient_cutoff,
                                     1 - min(rocr_list_viral[1,1][[1]]@cutoffs[[1]][rocr_list_viral[2,1][[1]]@y.values[[1]] >
                                                                                        rocr_list_viral[2,1][[1]]@x.values[[1]]], na.rm = T),
                                     1 - min(rocr_list_viral[1,1][[1]]@cutoffs[[1]][rocr_list_viral[2,1][[1]]@y.values[[1]] > stringent_prec],
                                             na.rm = T))
    } 
    
    big_plot_viral = mPlotAnnotVenn(filter_by_domain_data = filter_by_domain_data,
                                    motif_pval_cutoffs = motif_pval_cutoffs_viral,
                                    motif_pval_tags = motif_pval_tags,
                                    dataset = datasets[3], datasets = datasets, fontfamily = fontfamily)
    viral_grob = textGrob("only viral-human data",
                          gp=gpar(fontsize=25, fontfamily = fontfamily,
                                  lineheight = 1.4, ...))
    
    big_plot = gridExtra::arrangeGrob(big_plot_IntAct, big_plot_Vidal, big_plot_viral, nrow=1)
    big_text = gridExtra::arrangeGrob(IntAct_grob, Vidal_grob, viral_grob, nrow=1)
    big_plot_text = gridExtra::arrangeGrob(big_text, big_plot, ncol=1,
                                           layout_matrix = matrix(c(1,rep(2,6)),
                                                                  nrow = 7, ncol = 1))
    if(main != ""){
        main_grob = textGrob(main,
                          gp=gpar(fontsize=27, fontfamily = fontfamily,
                                  lineheight = 1, ...))
        big_plot_text = gridExtra::arrangeGrob(main_grob, big_plot_text, ncol=1,
                                           layout_matrix = matrix(c(1,rep(2,7)),
                                                                  nrow = 8, ncol = 1))
    }
    
    list(big_plot_text = big_plot_text,
         res_list_IntAct = res_list_IntAct, rocr_list_IntAct = rocr_list_IntAct, 
         res_list_Vidal = res_list_Vidal, rocr_list_Vidal = rocr_list_Vidal,
         res_list_viral = res_list_viral, rocr_list_viral = rocr_list_viral, 
         big_plot_IntAct = big_plot_IntAct, IntAct_grob = IntAct_grob,
         big_plot_Vidal = big_plot_Vidal, Vidal_grob = Vidal_grob,
         big_plot_viral = big_plot_viral, viral_grob = viral_grob)
}
#####################################################################################
replotFigureVenn = function(figure, main, fontfamily = "Arial", ...){
    IntAct_grob = textGrob("including all human data (IntAct)",
                           gp=gpar(fontsize=24, fontfamily = fontfamily,
                                   lineheight = 1, ...))
    Vidal_grob = textGrob("including human data (Vidal)",
                           gp=gpar(fontsize=24, fontfamily = fontfamily,
                                   lineheight = 1, ...))
    viral_grob = textGrob("only viral-human data",
                          gp=gpar(fontsize=24, fontfamily = fontfamily,
                                  lineheight = 1, ...))
    
    big_plot = gridExtra::arrangeGrob(rectGrob(gp=gpar(col = "white")),
                                      figure$big_plot_viral,
                                      rectGrob(gp=gpar(col = "white")),
                                      figure$big_plot_IntAct,
                                      rectGrob(gp=gpar(col = "white")),
                                      figure$big_plot_Vidal, nrow=1,
                                      layout_matrix = matrix(c(1,rep(2,6),
                                                               3,rep(4,6),
                                                               5,rep(6,6)),
                                                                  nrow = 1, ncol = 21))
    big_text = gridExtra::arrangeGrob(viral_grob, IntAct_grob, Vidal_grob, nrow=1)
    big_plot_text = gridExtra::arrangeGrob(big_text, big_plot, ncol=1,
                                           layout_matrix = matrix(c(1,rep(2,7)),
                                                                  nrow = 8, ncol = 1))
    if(main != ""){
        main_grob = textGrob(main,
                          gp=gpar(fontsize=27, fontfamily = fontfamily,
                                  lineheight = 1, ...))
        big_plot_text = gridExtra::arrangeGrob(main_grob, big_plot_text, ncol=1,
                                           layout_matrix = matrix(c(1,rep(2,7)),
                                                                  nrow = 8, ncol = 1))
    }
    list(big_plot_text = big_plot_text,
         res_list_IntAct = figure$res_list_IntAct, rocr_list_IntAct = figure$rocr_list_IntAct, 
         res_list_Vidal = figure$res_list_Vidal, rocr_list_Vidal = figure$rocr_list_Vidal,
         res_list_viral = figure$res_list_viral, rocr_list_viral = figure$rocr_list_viral, 
         big_plot_IntAct = figure$big_plot_IntAct, IntAct_grob = IntAct_grob,
         big_plot_Vidal = figure$big_plot_Vidal, Vidal_grob = Vidal_grob,
         big_plot_viral = figure$big_plot_viral, viral_grob = viral_grob)
}
##################################################################################### "MOD", "LIG", "DOC"

figureMODLIGDOC = figureVenn(filter_by_domain_data = NULL,
                    main = "human network searched for motifs present in viral proteins (not filtered by domain)",
                    motif_pval_tags = c("lenient cutoff", "optimal cutoff", "stringent cutoff"),
                    datasets = datasets,
                    motif_pval_cutoffs_viral = c(0.3, 0.1, 0.03))
figureMODLIGDOC2 = replotFigureVenn(figureMODLIGDOC,
                 main = "")
ggsave(filename = "Venn_not_filtered_MOD_LIG_DOC.svg", plot = figureMODLIGDOC2$big_plot_text,
       device = "svg", width = 19.3, height = 11.60638, units = "in")
#grid.newpage()
#grid.draw(figure2$big_plot_text)

figureMODLIGDOC2_filtered = figureVenn(filter_by_domain_data = "p.value < 0.5",
                             main = "human network searched for motifs present in viral proteins (filtered by domain)",
                             motif_pval_tags = c("lenient cutoff", "optimal cutoff", "stringent cutoff"),
                             datasets = datasets)
figureMODLIGDOC2_filtered2 = replotFigureVenn(figureMODLIGDOC2_filtered,
                 main = "")
ggsave(filename = "Venn_filtered_MOD_LIG_DOC.svg", plot = figureMODLIGDOC2_filtered2$big_plot_text,
       device = "svg", width = 19.3, height = 11.60638, units = "in")
#grid.newpage()
#grid.draw(figure_filtered2$big_plot_text)
##################################################################################### ^ copy optimal and stringent motif_pval_cutoffs
##################################################################################### "MOD", "LIG", "DOC", "DEG", "CLV"
motif_types = c("MOD", "LIG", "DOC", "DEG", "CLV")

figureMODLIGDOC2DEGCLV = figureVenn(filter_by_domain_data = NULL,
                    main = "human network searched for motifs present in viral proteins (not filtered by domain)",
                    motif_pval_tags = c("lenient cutoff", "optimal cutoff", "stringent cutoff"),
                    datasets = datasets,
                    motif_pval_cutoffs_IntAct = c(0.3, 0.063, 0.003),
                    motif_pval_cutoffs_Vidal = c(0.3, 0.069, 8e-05),
                    motif_pval_cutoffs_viral = c(0.3, 0.1, 0.03))
figureMODLIGDOC2DEGCLV2 = replotFigureVenn(figureMODLIGDOC2DEGCLV,
                 main = "")
ggsave(filename = "Venn_not_filtered_MOD_LIG_DOC_DEG_CLV.svg", plot = figureMODLIGDOC2DEGCLV2$big_plot_text,
       device = "svg", width = 19.3, height = 11.60638, units = "in")
#grid.newpage()
#grid.draw(figure2$big_plot_text)

figureMODLIGDOC2DEGCLV_filtered = figureVenn(filter_by_domain_data = "p.value < 0.5",
                             main = "human network searched for motifs present in viral proteins (filtered by domain)",
                             motif_pval_tags = c("lenient cutoff", "optimal cutoff", "stringent cutoff"),
                             datasets = datasets,
                    motif_pval_cutoffs_IntAct = c(0.3, 0.039, 0.002),
                    motif_pval_cutoffs_Vidal = c(0.3, 0.027, 7.4e-05),
                    motif_pval_cutoffs_viral = c(0.3, 0.14, 0.04))
figureMODLIGDOC2DEGCLV_filtered2 = replotFigureVenn(figureMODLIGDOC2DEGCLV_filtered,
                 main = "")
ggsave(filename = "Venn_filtered_MOD_LIG_DOC_DEG_CLV.svg", plot = figureMODLIGDOC2DEGCLV_filtered2$big_plot_text,
       device = "svg", width = 19.3, height = 11.60638, units = "in")
#grid.newpage()
#grid.draw(figure_filtered2$big_plot_text)
##################################################################################### "MOD", "LIG", "DOC" "DEG", "CLV", "TRG"
motif_types = c("MOD", "LIG", "DOC", "DEG", "CLV", "TRG")

figureMODLIGDOC2DEGCLVTRG = figureVenn(filter_by_domain_data = NULL,
                    main = "human network searched for motifs present in viral proteins (not filtered by domain)",
                    motif_pval_tags = c("lenient cutoff", "optimal cutoff", "stringent cutoff"),
                    datasets = datasets,
                    motif_pval_cutoffs_IntAct = c(0.3, 0.063, 0.003),
                    motif_pval_cutoffs_Vidal = c(0.3, 0.069, 8e-05),
                    motif_pval_cutoffs_viral = c(0.3, 0.1, 0.03))
figureMODLIGDOC2DEGCLVTRG2 = replotFigureVenn(figureMODLIGDOC2DEGCLVTRG,
                 main = "")
ggsave(filename = "Venn_not_filtered_MOD_LIG_DOC_DEG_CLV_TRG.svg", plot = figureMODLIGDOC2DEGCLVTRG2$big_plot_text,
       device = "svg", width = 19.3, height = 11.60638, units = "in")
#grid.newpage()
#grid.draw(figure2$big_plot_text)

figureMODLIGDOC2DEGCLVTRG_filtered = figureVenn(filter_by_domain_data = "p.value < 0.5",
                             main = "human network searched for motifs present in viral proteins (filtered by domain)",
                             motif_pval_tags = c("lenient cutoff", "optimal cutoff", "stringent cutoff"),
                             datasets = datasets,
                    motif_pval_cutoffs_IntAct = c(0.3, 0.039, 0.002),
                    motif_pval_cutoffs_Vidal = c(0.3, 0.027, 7.4e-05),
                    motif_pval_cutoffs_viral = c(0.3, 0.14, 0.04))
figureMODLIGDOC2DEGCLVTRG_filtered2 = replotFigureVenn(figureMODLIGDOC2DEGCLVTRG_filtered,
                 main = "")
ggsave(filename = "Venn_filtered_MOD_LIG_DOC_DEG_CLV_TRG.svg", plot = figureMODLIGDOC2DEGCLVTRG_filtered2$big_plot_text,
       device = "svg", width = 19.3, height = 11.60638, units = "in")
#grid.newpage()
#grid.draw(figure_filtered2$big_plot_text)
#####################################################################################
```

# protein-domain-motif-protein network

```{r}
# get motif & domains (stringent threshold)
IntAct = myBenchmarkMotifs(neg_set = "all_proteins",
                  filter_by_domain_data = "p.value < 0.5",
                  motif_pval_cutoff = 0.002,
                  dataset = datasets[1], datasets,
                  return_all = T, merge_domain_data = T)
viral = myBenchmarkMotifs(neg_set = "all_proteins",
                  filter_by_domain_data = "p.value < 0.5",
                  motif_pval_cutoff = 0.04,
                  dataset = datasets[3], datasets,
                  return_all = T, merge_domain_data = T)

bechmark2Net = function(occurence_query = IntAct$res$qslimfinder.Full_IntAct3.FALSE$occurence_query,
                        matching_known = IntAct$res$qslimfinder.Full_IntAct3.FALSE$overlapping_GRanges_query) {
Net = data.table(Viral_protein = occurence_query$query,
                        Motif_Sig = occurence_query$Sig,
                        Domain_p.value = occurence_query$p.value,
                        Pattern = occurence_query$Pattern,
                        Human_recognition_domain = occurence_query$IDs_domain_human,
                        Human_protein = occurence_query$interacts_with,
                        unique_position = paste0(GenomicRanges::seqnames(occurence_query), "_",
                                              GenomicRanges::start(occurence_query), "_",
                                              GenomicRanges::end(occurence_query)))
Net = unique(Net)
Net[, top_domain := Domain_p.value == min(Domain_p.value), by = unique_position]
Net = Net[top_domain == TRUE]
Net[, top_domain := NULL]

matching_known = data.table(unique_position = paste0(GenomicRanges::seqnames(matching_known), "_",
                                                     GenomicRanges::start(matching_known), "_",
                                                     GenomicRanges::end(matching_known)),
                            matching_known = "matching_known")
Net = merge(Net, matching_known, by = "unique_position", all.x = T, all.y = F, allow.cartesian=TRUE)
unique(Net)
}

IntAct_net = bechmark2Net(occurence_query = IntAct$res$qslimfinder.Full_IntAct3.FALSE$occurence_query,
                        matching_known = IntAct$res$qslimfinder.Full_IntAct3.FALSE$overlapping_GRanges_query)
viral_net = bechmark2Net(occurence_query = viral$res$qslimfinder.all_viral_interaction3.FALSE$occurence_query,
                        matching_known = viral$res$qslimfinder.all_viral_interaction3.FALSE$overlapping_GRanges_query)
```

```{r, eval=FALSE}
# get readable names for proteins and domains 
readableNet = function(Net){
    proteins2gene_names = lapply(unique(c(Net$Viral_protein, Net$Human_protein)), function(uniprot_id) {
        suppressMessages({
            proteins2gene_names = fread(paste0("https://www.uniprot.org/uniprot/?query=id:", uniprot_id,
                                               "&format=tab&columns=id,genes,entry%20name,protein%20names,organism,organism-id"),
                                        stringsAsFactors = F)
        })
        proteins2gene_names
    })
    proteins2gene_names = Reduce(rbind, proteins2gene_names)
    setnames(proteins2gene_names, colnames(proteins2gene_names),
             c( "Entry", "Gene_names", "Entry_name", "Protein_names", "Organism", "Organism_ID"))
    proteins2gene_names[, Gene_names := gsub(" .*", "", Gene_names)] # pick only first gene name
    proteins2gene_names[, Protein_names := gsub(" \\(.*", "", Protein_names)] # pick only first protein name
    # fwrite(proteins2gene_names, "./results/IntAct_network_proteins2gene_names", sep = "\t")
    proteins2gene_names_human = proteins2gene_names[Organism_ID == 9606]
    proteins2gene_names_viral = proteins2gene_names[Organism_ID != 9606]
    
    proteins2gene_names_human[, c("Organism", "Organism_ID") := NULL]
    proteins2gene_names_viral[, c("Organism", "Organism_ID") := NULL]
    
    setnames(proteins2gene_names_human, colnames(proteins2gene_names_human),
             c("Human_protein", "Human_gene_names", "Human_entry_name", "Human_protein_names"))
    setnames(proteins2gene_names_viral, colnames(proteins2gene_names_viral),
             c("Viral_protein", "Viral_gene_names", "Viral_entry_name", "Viral_protein_names"))
    
    Net = merge(Net, proteins2gene_names_human, by = "Human_protein", all.x = T, all.y = F)
    Net = merge(Net, proteins2gene_names_viral, by = "Viral_protein", all.x = T, all.y = F)
    
    InterProEntryTypes = getInterProEntryTypes("./data_files/entry.list")
    InterProEntryTypes[, ENTRY_TYPE := NULL]
    setnames(InterProEntryTypes, colnames(InterProEntryTypes),
             c("Human_recognition_domain", "Human_recognition_domain_name"))
    Net = merge(Net, InterProEntryTypes, by = "Human_recognition_domain", all.x = T, all.y = F)
    
    # reorder column names 
    Net = Net[, .(Pattern, Human_recognition_domain_name, Domain_p.value,
                  Viral_protein, Human_protein, matching_known,
                  Viral_protein_names, Viral_entry_name, Human_protein_names, Human_entry_name,
                  Human_recognition_domain, Motif_Sig, unique_position,
                  Viral_gene_names, Human_gene_names)]
    setorder(Net, Viral_protein, Motif_Sig, Domain_p.value)
    unique(Net)
}

IntAct_net = readableNet(IntAct_net)
viral_net = readableNet(viral_net)

fwrite(IntAct_net, "./results/IntAct_net_motif_domain_readable", sep = "\t")
fwrite(viral_net, "./results/viral_net_motif_domain_readable", sep = "\t")

fwrite(unique(IntAct_net[,.(Pattern)]), "./results/IntAct_net_patterns", sep = "\t")
fwrite(unique(viral_net[,.(Pattern)]), "./results/viral_net_patterns", sep = "\t")
```

```{r}
# reconstruct GRanges into network
dataset4Cytoscape = function(uniprot_id = "P03126")
    IntAct_GRanges =  IntAct$res$qslimfinder.Full_IntAct3.FALSE$occurence_query
Nrows = length(IntAct_GRanges)
IntAct_network = data.table(source = c(IntAct_GRanges$interacts_with,   IntAct_GRanges$IDs_domain_human, IntAct_GRanges$Pattern),
                            target = c(IntAct_GRanges$IDs_domain_human, IntAct_GRanges$Pattern,          IntAct_GRanges$query),
                            Sig =    c(rep(1, Nrows),                   IntAct_GRanges$Sig,              rep(1, Nrows)),
                            type_source = c(rep("human_protein", Nrows), rep("human_domain", Nrows),  rep("viral_motif", Nrows)),
                            type_target = c(rep("human_domain", Nrows), rep("viral_motif", Nrows),  rep("viral_protein", Nrows)))
IntAct_network = unique(IntAct_network[complete.cases(IntAct_network)])
IntAct_network_types = unique(data.table(node = c(IntAct_network$source, IntAct_network$target),
                                         type = c(IntAct_network$type_source, IntAct_network$type_target)))
fwrite(IntAct_network, "./results/IntAct_network", sep = "\t")
fwrite(IntAct_network_types, "./results/IntAct_network_types", sep = "\t")

#################################################  recovered motifs network
IntAct_GRanges_rec =  IntAct$res$qslimfinder.Full_IntAct3.FALSE$overlapping_GRanges_query
Nrows = length(IntAct_GRanges_rec)
IntAct_network_rec = data.table(source = c(IntAct_GRanges_rec$interacts_with,   IntAct_GRanges_rec$IDs_domain_human, IntAct_GRanges_rec$Pattern),
                                target = c(IntAct_GRanges_rec$IDs_domain_human, IntAct_GRanges_rec$Pattern,          IntAct_GRanges_rec$query),
                                Sig =    c(rep(1, Nrows),                   IntAct_GRanges_rec$Sig,              rep(1, Nrows)),
                                type_source = c(rep("human_protein", Nrows), rep("human_domain", Nrows),  rep("viral_motif", Nrows)),
                                type_target = c(rep("human_domain", Nrows), rep("viral_motif", Nrows),  rep("viral_protein", Nrows)))
IntAct_network_rec = unique(IntAct_network_rec[complete.cases(IntAct_network_rec)])
IntAct_network_rec_types = unique(data.table(node = c(IntAct_network_rec$source, IntAct_network_rec$target),
                                             type = c(IntAct_network_rec$type_source, IntAct_network_rec$type_target)))
fwrite(IntAct_network_rec, "./results/IntAct_network_rec", sep = "\t")
fwrite(IntAct_network_rec_types, "./results/IntAct_network_rec_types", sep = "\t")
#################################################  recovered motifs network for P03126
IntAct_GRanges_rec =  IntAct$res$qslimfinder.Full_IntAct3.FALSE$overlapping_GRanges_query
IntAct_GRanges_rec = IntAct_GRanges_rec[IntAct_GRanges_rec$query == "P03126"]
Nrows = length(IntAct_GRanges_rec)
IntAct_network_rec = data.table(source = c(IntAct_GRanges_rec$interacts_with,   IntAct_GRanges_rec$IDs_domain_human, IntAct_GRanges_rec$Pattern),
                                target = c(IntAct_GRanges_rec$IDs_domain_human, IntAct_GRanges_rec$Pattern,          IntAct_GRanges_rec$query),
                                Sig =    c(rep(1, Nrows),                   IntAct_GRanges_rec$Sig,              rep(1, Nrows)),
                                type_source = c(rep("human_protein", Nrows), rep("human_domain", Nrows),  rep("viral_motif", Nrows)),
                                type_target = c(rep("human_domain", Nrows), rep("viral_motif", Nrows),  rep("viral_protein", Nrows)))
IntAct_network_rec = unique(IntAct_network_rec[complete.cases(IntAct_network_rec)])
IntAct_network_rec_types = unique(data.table(node = c(IntAct_network_rec$source, IntAct_network_rec$target),
                                             type = c(IntAct_network_rec$type_source, IntAct_network_rec$type_target)))
domain_prop_P03126 = unique(data.table(node = IntAct_GRanges_rec$IDs_domain_human,
                                       p.value = IntAct_GRanges_rec$p.value))
fwrite(IntAct_network_rec, "./results/IntAct_network_recP03126", sep = "\t")
fwrite(IntAct_network_rec_types, "./results/IntAct_network_rec_typesP03126", sep = "\t")
fwrite(domain_prop_P03126, "./results/domain_prop_P03126", sep = "\t")
#################################################  recovered motifs network for P03428
IntAct_GRanges_rec =  IntAct$res$qslimfinder.Full_IntAct3.FALSE$overlapping_GRanges_query
IntAct_GRanges_rec = IntAct_GRanges_rec[IntAct_GRanges_rec$query == "P03428"]
Nrows = length(IntAct_GRanges_rec)
IntAct_network_rec = data.table(source = c(IntAct_GRanges_rec$interacts_with,   IntAct_GRanges_rec$IDs_domain_human, IntAct_GRanges_rec$Pattern),
                                target = c(IntAct_GRanges_rec$IDs_domain_human, IntAct_GRanges_rec$Pattern,          IntAct_GRanges_rec$query),
                                Sig =    c(rep(1, Nrows),                   IntAct_GRanges_rec$Sig,              rep(1, Nrows)),
                                type_source = c(rep("human_protein", Nrows), rep("human_domain", Nrows),  rep("viral_motif", Nrows)),
                                type_target = c(rep("human_domain", Nrows), rep("viral_motif", Nrows),  rep("viral_protein", Nrows)))
IntAct_network_rec = unique(IntAct_network_rec[complete.cases(IntAct_network_rec)])
IntAct_network_rec_types = unique(data.table(node = c(IntAct_network_rec$source, IntAct_network_rec$target),
                                             type = c(IntAct_network_rec$type_source, IntAct_network_rec$type_target)))
domain_prop_P03428 = unique(data.table(node = IntAct_GRanges_rec$IDs_domain_human,
                                       p.value = IntAct_GRanges_rec$p.value))
fwrite(IntAct_network_rec, "./results/IntAct_network_recP03428", sep = "\t")
fwrite(IntAct_network_rec_types, "./results/IntAct_network_rec_typesP03428", sep = "\t")
fwrite(domain_prop_P03428, "./results/domain_prop_P03428", sep = "\t")
#################################################  recovered motifs network for P06463
IntAct_GRanges_rec =  IntAct$res$qslimfinder.Full_IntAct3.FALSE$overlapping_GRanges_query
IntAct_GRanges_rec = IntAct_GRanges_rec[IntAct_GRanges_rec$query == "P06463"]
Nrows = length(IntAct_GRanges_rec)
IntAct_network_rec = data.table(source = c(IntAct_GRanges_rec$interacts_with,   IntAct_GRanges_rec$IDs_domain_human, IntAct_GRanges_rec$Pattern),
                            target = c(IntAct_GRanges_rec$IDs_domain_human, IntAct_GRanges_rec$Pattern,          IntAct_GRanges_rec$query),
                            Sig =    c(rep(1, Nrows),                   IntAct_GRanges_rec$Sig,              rep(1, Nrows)),
                            type_source = c(rep("human_protein", Nrows), rep("human_domain", Nrows),  rep("viral_motif", Nrows)),
                            type_target = c(rep("human_domain", Nrows), rep("viral_motif", Nrows),  rep("viral_protein", Nrows)))
IntAct_network_rec = unique(IntAct_network_rec[complete.cases(IntAct_network_rec)])
IntAct_network_rec_types = unique(data.table(node = c(IntAct_network_rec$source, IntAct_network_rec$target),
                                  type = c(IntAct_network_rec$type_source, IntAct_network_rec$type_target)))
domain_prop_P06463 = unique(data.table(node = IntAct_GRanges_rec$IDs_domain_human,
                                       p.value = IntAct_GRanges_rec$p.value))
fwrite(IntAct_network_rec, "./results/IntAct_network_recP06463", sep = "\t")
fwrite(IntAct_network_rec_types, "./results/IntAct_network_rec_typesP06463", sep = "\t")
fwrite(domain_prop_P06463, "./results/domain_prop_P06463", sep = "\t")
#################################################  candidate motifs network for P03070 ################################################
IntAct_GRanges_cand =  IntAct$res$qslimfinder.Full_IntAct3.FALSE$occurence_query
IntAct_GRanges_cand = IntAct_GRanges_cand[IntAct_GRanges_cand$query == "P03070"]
Nrows = length(IntAct_GRanges_cand)
IntAct_network_cand = data.table(source = c(IntAct_GRanges_cand$interacts_with,   IntAct_GRanges_cand$IDs_domain_human, IntAct_GRanges_cand$Pattern),
                            target = c(IntAct_GRanges_cand$IDs_domain_human, IntAct_GRanges_cand$Pattern,          IntAct_GRanges_cand$query),
                            Sig =    c(rep(1, Nrows),                   IntAct_GRanges_cand$Sig,              rep(1, Nrows)),
                            type_source = c(rep("human_protein", Nrows), rep("human_domain", Nrows),  rep("viral_motif", Nrows)),
                            type_target = c(rep("human_domain", Nrows), rep("viral_motif", Nrows),  rep("viral_protein", Nrows)))
IntAct_network_cand = unique(IntAct_network_cand[complete.cases(IntAct_network_cand)])
IntAct_network_cand_types = unique(data.table(node = c(IntAct_network_cand$source, IntAct_network_cand$target),
                                  type = c(IntAct_network_cand$type_source, IntAct_network_cand$type_target)))
domain_prop_P03070 = unique(data.table(node = IntAct_GRanges_cand$IDs_domain_human,
                                       p.value = IntAct_GRanges_cand$p.value))
fwrite(IntAct_network_cand, "./results/IntAct_network_candP03070", sep = "\t")
fwrite(IntAct_network_cand_types, "./results/IntAct_network_cand_typesP03070", sep = "\t")
fwrite(domain_prop_P03070, "./results/domain_prop_P03070", sep = "\t")
#################################################  candidate motifs network for Q2PJP0 #################################################
IntAct_GRanges_cand =  IntAct$res$qslimfinder.Full_IntAct3.FALSE$occurence_query
IntAct_GRanges_cand = IntAct_GRanges_cand[IntAct_GRanges_cand$query == "Q2PJP0"]
Nrows = length(IntAct_GRanges_cand)
IntAct_network_cand = data.table(source = c(IntAct_GRanges_cand$interacts_with,   IntAct_GRanges_cand$IDs_domain_human, IntAct_GRanges_cand$Pattern),
                            target = c(IntAct_GRanges_cand$IDs_domain_human, IntAct_GRanges_cand$Pattern,          IntAct_GRanges_cand$query),
                            Sig =    c(rep(1, Nrows),                   IntAct_GRanges_cand$Sig,              rep(1, Nrows)),
                            type_source = c(rep("human_protein", Nrows), rep("human_domain", Nrows),  rep("viral_motif", Nrows)),
                            type_target = c(rep("human_domain", Nrows), rep("viral_motif", Nrows),  rep("viral_protein", Nrows)))
IntAct_network_cand = unique(IntAct_network_cand[complete.cases(IntAct_network_cand)])
IntAct_network_cand_types = unique(data.table(node = c(IntAct_network_cand$source, IntAct_network_cand$target),
                                  type = c(IntAct_network_cand$type_source, IntAct_network_cand$type_target)))
domain_prop_Q2PJP0 = unique(data.table(node = IntAct_GRanges_cand$IDs_domain_human,
                                       p.value = IntAct_GRanges_cand$p.value))
fwrite(IntAct_network_cand, "./results/IntAct_network_candQ2PJP0", sep = "\t")
fwrite(IntAct_network_cand_types, "./results/IntAct_network_cand_typesQ2PJP0", sep = "\t")
fwrite(domain_prop_Q2PJP0, "./results/domain_prop_Q2PJP0", sep = "\t")
#################################################  candidate motifs network for Q67296 #################################################
IntAct_GRanges_cand =  IntAct$res$qslimfinder.Full_IntAct3.FALSE$occurence_query
IntAct_GRanges_cand = IntAct_GRanges_cand[IntAct_GRanges_cand$query == "Q67296"]
Nrows = length(IntAct_GRanges_cand)
IntAct_network_cand = data.table(source = c(IntAct_GRanges_cand$interacts_with,   IntAct_GRanges_cand$IDs_domain_human, IntAct_GRanges_cand$Pattern),
                            target = c(IntAct_GRanges_cand$IDs_domain_human, IntAct_GRanges_cand$Pattern,          IntAct_GRanges_cand$query),
                            Sig =    c(rep(1, Nrows),                   IntAct_GRanges_cand$Sig,              rep(1, Nrows)),
                            type_source = c(rep("human_protein", Nrows), rep("human_domain", Nrows),  rep("viral_motif", Nrows)),
                            type_target = c(rep("human_domain", Nrows), rep("viral_motif", Nrows),  rep("viral_protein", Nrows)))
IntAct_network_cand = unique(IntAct_network_cand[complete.cases(IntAct_network_cand)])
IntAct_network_cand_types = unique(data.table(node = c(IntAct_network_cand$source, IntAct_network_cand$target),
                                  type = c(IntAct_network_cand$type_source, IntAct_network_cand$type_target)))
domain_prop_Q67296 = unique(data.table(node = IntAct_GRanges_cand$IDs_domain_human,
                                       p.value = IntAct_GRanges_cand$p.value))
fwrite(IntAct_network_cand, "./results/IntAct_network_candQ67296", sep = "\t")
fwrite(IntAct_network_cand_types, "./results/IntAct_network_cand_typesQ67296", sep = "\t")
fwrite(domain_prop_Q67296, "./results/domain_prop_Q67296", sep = "\t")
```


```{r, exit}
Sys.Date. = Sys.Date()
Sys.Date.
session_info. = devtools::session_info()
session_info.
filename = paste0("./processed_data_files/compr_benchmarking_venn_IntVidVir",format(Sys.Date., "%Y%m"),"_type_", measure1, measure2,".RData")
save(list = ls(), file=filename)
```