---
title: "InterPro_entry_types"
author: "Vitalii Kleshchevnikov"
date: "22/06/2017"
output: 
  html_document: 
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
packages = c("data.table","downloader","DT")

if(mean(packages %in% names(installed.packages()[,"Package"])) != 1){
      packages_to_install = packages[!packages %in% names(installed.packages()[,"Package"])]
      install.packages(packages_to_install)
      packages_to_install = packages[!packages %in% names(installed.packages()[,"Package"])]
      source("https://bioconductor.org/biocLite.R")
      biocLite(packages_to_install)
}

suppressPackageStartupMessages({
    library(data.table)
    library(downloader)
    library(DT)
})
```

## Downloading InterPro entry.list

```{r}
url = "ftp://ftp.ebi.ac.uk/pub/databases/interpro/entry.list"
file = "./data_files/InterPro.entry.list.txt"
download(url, file)
```

## Reading InterPro entry.list and converting it into the table

```{r}
InterPro_entry = readLines(file)
types = which(substr(InterPro_entry, 1, 3) != "IPR")

InterPro_entry_types = data.table()
for(x in 1:(length(types)-1)) {
    InterPro_entry_types = rbind(InterPro_entry_types, data.table(INTERPRO_ID = substr(InterPro_entry[(types[x]+1):(types[x+1]-1)],1,9), 
               INTERPRO_NAME = substr(InterPro_entry[(types[x]+1):(types[x+1]-1)],10,
                                      nchar(InterPro_entry[(types[x]+1):(types[x+1]-1)])), 
               ENTRY_TYPE = InterPro_entry[types[x]]))
}
```

## Saving InterPro entry_types table

```{r}
fwrite(InterPro_entry_types, "./processed_data_files/InterPro_entry_types.txt", sep = "\t")
```

## Interactive InterPro entry_types table

```{r}
datatable(InterPro_entry_types)
```