---
title: "Mapping domains to the protein interaction network"
author: "Vitalii Kleshchevnikov"
date: "29/06/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

packages = c("data.table","downloader","R.utils","UniProt.ws", "PSICQUIC", "ggplot2", "rtracklayer", "Biostrings", "queryPSICQUIC")
if(mean(packages %in% names(installed.packages()[,"Package"])) != 1){
      packages_to_install = packages[!packages %in% names(installed.packages()[,"Package"])]
      install.packages(packages_to_install)
      packages_to_install = packages[!packages %in% names(installed.packages()[,"Package"])]
      source("https://bioconductor.org/biocLite.R")
      biocLite(packages_to_install)
      devtools::install_github("vitkl/viral_project/queryPSICQUIC")
}

suppressPackageStartupMessages({
    library(data.table)
    library(downloader)
    library(R.utils)
    library(UniProt.ws)
    library(PSICQUIC)
    library(ggplot2)
    library(rtracklayer)
    library(Biostrings)
    library(queryPSICQUIC)
    source("viral_functions.R")
})
```

## Read InterProScan result and filter for "Domain", "Active_site", "Binding_site", "Conserved_site", "PTM" signatures

I read interaction data and clean this data to make it more useble. Then, I filter and keep only human-viral interactions.

```{r human_viral}
all_viral_interaction = fread("./data_files/human_viral_interactions.txt", stringsAsFactors = F)

# changing column names to data.table-compatible format
{
colnames(all_viral_interaction) = gsub(" ","_",colnames(all_viral_interaction))
colnames(all_viral_interaction) = gsub("\\(|\\)","",colnames(all_viral_interaction))
colnames(all_viral_interaction) = gsub("#","",colnames(all_viral_interaction))
}
# cleaning Taxid "taxid:9606(human)|taxid:9606(Homo sapiens)" to 9606
{
all_viral_interaction[, Taxid_interactor_A := gsub("taxid:|\\(.*$","",Taxid_interactor_A)]
all_viral_interaction[, Taxid_interactor_B := gsub("taxid:|\\(.*$","",Taxid_interactor_B)]
all_viral_interaction[, Host_organisms := gsub("taxid:|\\(.*$","",Host_organisms)]
# saving identifier types and cleaning interactor ids
all_viral_interaction[, interactor_IDs_databases_A := gsub(":.*$","",IDs_interactor_A)]
all_viral_interaction[, interactor_IDs_databases_B := gsub(":.*$","",IDs_interactor_B)]
all_viral_interaction[, IDs_interactor_A := gsub("^.*:","",IDs_interactor_A)]
all_viral_interaction[, IDs_interactor_B := gsub("^.*:","",IDs_interactor_B)]
# isoform "-1" is a canonical sequence, IntAct uses isoform "-1" when it's clear that the isoform is "-1" and a canonical identifier if it's not clear which isoform was used in the experiment. Removing isoform sign "-1":
all_viral_interaction[, IDs_interactor_A := gsub("-1$", "", IDs_interactor_A)]
all_viral_interaction[, IDs_interactor_B := gsub("-1$", "", IDs_interactor_B)]
# removing interactions if at least one interactor has non-uniprot id
all_viral_interaction = all_viral_interaction[interactor_IDs_databases_A == "uniprotkb",][interactor_IDs_databases_B == "uniprotkb",]
# cleaning other information
all_viral_interaction[, bait_prey_status_A := gsub("^.*\\(|\\)","",Experimental_roles_interactor_A)]
all_viral_interaction[, bait_prey_status_B := gsub("^.*\\(|\\)","",Experimental_roles_interactor_B)]
all_viral_interaction[, Publication_Identifiers := gsub("^.*pubmed:|\\|.*$","",Publication_Identifiers)]
all_viral_interaction[, Confidence_values := gsub("^intact-miscore:","",Confidence_values)]
all_viral_interaction[, Confidence_values := gsub("-","NA",Confidence_values)]
all_viral_interaction[, Confidence_values := as.numeric(Confidence_values)]
#all_viral_interaction[, Interaction_identifiers := unlist(gsubfn::strapplyc(Interaction_identifiers,"EBI-[[:digit:]]+",simplify = T)), by =Interaction_identifiers]
# generating unique identifier for interacting pairs
all_viral_interaction[, pair_id := apply(data.table(IDs_interactor_A,IDs_interactor_B,stringsAsFactors = F), 1,
                                               function(a) { z = sort(a)
                                               paste0(z[1],"_",z[2]) })]
all_viral_interaction[, pair_species_id := apply(data.table(Taxid_interactor_A,Taxid_interactor_B,stringsAsFactors = F), 1,
                                               function(a) { z = sort(a)
                                               paste0(z[1],"_",z[2]) })]
}

# filter only human-viral interactions
all_viral_interaction = all_viral_interaction[Taxid_interactor_A == "9606" | Taxid_interactor_B == "9606",]
all_viral_interaction = unique(all_viral_interaction)
```

I read InterProScan result and the InterPro_entry_types file. InterProScan output format description: https://github.com/ebi-pf-team/interproscan/wiki/OutputFormats  

```{r InterPro_entry_types}
# read InterProScan result
InterProScan_result = import(con = "./processed_data_files/all_human_viral_protein_domains.gff3", format = "gff3")
# clean InterPro ID in the Dbxref column
InterProScan_result$Dbxref = gsub("InterPro:","", InterProScan_result$Dbxref)
InterProScan_result$Dbxref = gsub("\"","", InterProScan_result$Dbxref)
InterProScan_result$Ontology_term = gsub("\"","", InterProScan_result$Ontology_term)
# read InterPro_entry_types mapping table
InterPro_entry_types = fread("./processed_data_files/InterPro_entry_types.txt", stringsAsFactors = F)
# find matching signatures
matching_signatures = match(as.character(InterProScan_result$Dbxref), InterPro_entry_types$INTERPRO_ID)
# add signature type information to the gff2 file
InterProScan_result$ENTRY_TYPE = InterPro_entry_types$ENTRY_TYPE[matching_signatures]
# add names metadata to allow subsetting with a character
names(InterProScan_result) = seqnames(InterProScan_result)

# import seqence length information correctly into the GRanges object format
# find seqence length
seq_length = end(InterProScan_result)[InterProScan_result$type == "polypeptide"]
# name the vector
names(seq_length) = seqnames(InterProScan_result)[InterProScan_result$type == "polypeptide"]
# match names in the vector and in the GRanges seqlengths slot
seqlengths(InterProScan_result) = seq_length[match(names(seqlengths(InterProScan_result)),names(seq_length))]
# sanity check
seqlengths(InterProScan_result)[c("P69713", "P06748-3", "P06821", "O00562", "O15230")] == end(InterProScan_result[c("P69713", "P06748-3", "P06821", "O00562", "O15230")])


# create a subset that contains "Domain", "Active_site", "Binding_site", "Conserved_site", "PTM" signatures
InterProScan_domains = InterProScan_result[InterProScan_result$ENTRY_TYPE %in% c("Domain", "Active_site", "Binding_site", "Conserved_site", "PTM")]
```

## Map trimmed 