---
title: "DomainResultsTable: viral protein - human domain pairs"
author: "Vitalii Kleshchevnikov"
date: "17/08/2017"
output: 
  html_document: 
    keep_md: yes
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
packages = c("MItools", "DT")
if(mean(packages %in% names(installed.packages()[,"Package"])) != 1){
    packages_to_install = packages[!packages %in% names(installed.packages()[,"Package"])]
    # specifying mirror is necessary for some Linux systems
    install.packages(packages_to_install, dependencies = T, repos = "http://mirrors.ebi.ac.uk/CRAN/")
    packages_to_install = packages[!packages %in% names(installed.packages()[,"Package"])]
    source("https://bioconductor.org/biocLite.R")
    biocLite(packages_to_install, dependencies = T)
    devtools::install_github("vitkl/MItools", dependencies = T)
}

suppressPackageStartupMessages({
    library(MItools)
    library(DT)
})
```

# Load results

```{r load}
name = "./DomainResultsTable_Vidal20171019.RData"
if(!file.exists(name)){
    load("./processed_data_files/what_we_find_VS_ELM_clust20171019.RData")
    occurence_QSLIMFinder = fread("./SLIMFinder_Vidal/result/occurence.txt")
    comparimotif_wdb = fread("./SLIMFinder_Vidal/result/comparimotif.compare.tdt")
    rm(list = ls()[!ls() %in% c("printTable","XYZ.p.adjust","res_count", "sequential_filter", "name", "occurence_QSLIMFinder", "comparimotif_wdb")])
    save.image(file = name)
} else {
    load(name)
}
doman_viral_pairs = T # if false - add human proteins containing domains
motifs = T # based on Vidal's data
```

## Empirical p-value for seing a domain a number of times
### What is the chance of randomly seeing any domain the observed number of times among all proteins that interact with a specific viral protein

```{r sigdomain_sigmotif}
fdr_motifs = 1
fdr_pval_thresh = 1
X = printMotifDomainTable(res_count, doman_viral_pairs = doman_viral_pairs, motifs = motifs, destfile = "./domains_fdr_corrected_only_with_significant_motifs_empirical_p_value.tsv",
               only_with_motifs = T, fdr_motifs = fdr_motifs, fdr_pval_thresh = fdr_pval_thresh,
               occurence_QSLIMFinder = occurence_QSLIMFinder,
               comparimotif_wdb = comparimotif_wdb, print_table = F)
```

## Which motifs don't match ELM

```{r}
DT::datatable(X[is.na(motif_mapping)], escape = FALSE)
```